# Generated by Django 4.2 on 2023-04-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Shoes name')),
                ('price', models.PositiveIntegerField(verbose_name='Shoes price')),
                ('img', models.ImageField(upload_to='images', verbose_name='Shoes image')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Shoes create date')),
                ('about', models.TextField(verbose_name='Shoes about')),
            ],
            options={
                'verbose_name': 'Shoes',
                'verbose_name_plural': 'Shoes',
                'ordering': ['date'],
            },
        ),
    ]
