# Generated by Django 4.2 on 2023-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Shoes about'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Shoes about'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Shoes about'),
        ),
    ]
